### ISSUE TITLE
Move simulation code to this repository

### ISSUE THREAD

**Issue by sebhoerl** [eqasim-org/ile-de-france#1]
We need to discuss whether it makes sense to move the simulation code into this repository, or if it should stay at `eqasim-org/eqasim-java`.

**Comment by Nitnelav** [comment]
To me it would make sense to move the java project into a directory here. But I think it would be best to make this repository less `ile-de-france` centric first. In order to better match the way the eqasim-java project is organized maybe ?

**Comment by balacmi** [comment]
This is an interesting question. One might argue that the eqasim-java is completely based on the otuputs of this pipeline, but this repository is independent of the eqasim-java. Because of this my thinking is that maybe leaving it as is would make more sense. Probably would be nice to hear some arguments as to why merging them together would be a preferred option. 

I would agree also that it also does not have to be ile-de-france centric. @sebhoerl we can discuss this further I guess.

**Comment by sebhoerl** [comment]
- I was already thinking of renaming this repository here just to `france`, maybe. Since we're creating all kind of scenarios from it, like Toulouse and Lyon, even without making additional changes like for Nantes (or Lille). So in my view making the repository more "general" would rather be a matter of changing the name.

- Actually I have the feeling it would be better to move some Java code here. For instance, the latest changes where we added activity chains that do not need to start and end at home was a bit of going back and forth. First, I was changing the code here to generate those activity chains, then I was changing the code in `eqasim-java` to make the Java work with them. Then for testing I first needed to update `eqasim-java` with the latest Corsica scenario generated by the pipeline *without* the actiivty chain updates, to check if the tests in `eqasim-java` were still valid with the latest pipeline version. Then I manually needed to test running the old chain output (without new activity chains) with the new `eqasim-java` code to make sure that the new Java code doesn't change anything. And then I updated the Corsica test data in `eqasim-java` with the new pipeline output, etc.

The problem is that the pipeline depends on `eqasim-java` for a lot of stuff when generating the MATSim scenario, and then running it. But the `eqasim-java` repository depends on the format of the pipeline output. So in a way this is circular and some chicken and egg problem. 

Ideally, there is some general `eqasim-java` code that is common to all scenarios (also San Francisco, Sao Paulo, ...) and a specific part for each scenario. This, we basically already have, because `eqasim-java` contains sub-projects for all scenarios. So I would move this part here, the question is then how do we proceed with Bintray packages etc.

**Comment by Nitnelav** [comment]
Indeed, the two projects seem doomed to be interdependent in their current form.
Moving eqasim-java sub-projects to this repo ("eqasim-france" ?) and keeping the org.eqasim.core package in a separate repo, available as a bintray dependency seems like a good option to me !

**Comment by Nitnelav** [comment]
The current decision is to keep them separate, and to separate them more !

**Comment by sebhoerl** [comment]
Indeed :D
