### ISSUE TITLE
Could this tool use for other region?

### ISSUE THREAD

**Issue by sinkan851014** [eqasim-org/ile-de-france#103]
Hi,
I want to know if I could change data or a little part of code to creat SP in other region out of france.
And If could, anything should be noticed.

Thanks!

Cooper

**Comment by sebhoerl** [comment]
Hi, there are implementations for 

- [Sao Paulo](https://github.com/eqasim-org/sao_paulo)
- [Jakarta](https://github.com/eqasim-org/jakarta)
- [California](https://github.com/eqasim-org/california)

There is no recipe for how to port the approach to a different city. It depends a lot on if and which data is available to you. To get an idea, read the paper on the Ile-de-France pipeline and then compare with the papers for California and Sao Paulo. This will give you an idea which are the things that need to be changed.
