### ISSUE TITLE
PT agents don't use PT links

### ISSUE THREAD

**Issue by G14LL0** [eqasim-org/ile-de-france#106]
Hi,
I'm testing around this simulation approach, since I'd like to apply it also in other regions. After some tries it all ran smoothly, but it seems that the simulation output does not take into account the PT routes. 

Looking at the output files, the PT is an used mode, with a realistic modal share, and visualizing the plans.xlm.gz in Simunto Via, the PT is actually included in the trips, so all good till here.
The problem, I think, is that the passengers are not associated to the actual transit routes and thus the activity is know (PT), but the agent teleports. Infact in the plans.xlm.gz the car vehicles are routed, the PT vehicles are not. Similarly to bike and walk, but as far as I understand those are actually teleported modes.
Do you have a tip on how to solve this?

I'm attaching an image for reference. 

![image](https://user-images.githubusercontent.com/26892250/160237917-5ad38c6a-2c07-4a05-9440-6ae3f95932ae.png)

Thanks,
Federico

**Comment by sebhoerl** [comment]
In our eqasim scenarios we use a customized version of MATSim where we, for instance, use discrete choice models to perform the choices of the agents. Also different to standard MATSim, we teleport the PT mode, but based on the schedule. We have a custom simulation engine as part of the https://github.com/eqasim-org/eqasim-java package. You can enable network-based simulation by setting `useScheduleBasedTransport` to `false` in the `eqasim` config group: https://github.com/eqasim-org/eqasim-java/blob/develop/core/src/main/java/org/eqasim/core/components/config/EqasimConfigGroup.java

**Comment by G14LL0** [comment]
Thanks a lot for the reply. 
With your suggestion I managed to have the routing, but now I see why you are opting for the teleport of PT, it really doesn't add that much information to the simulation.
