### ISSUE TITLE
Perform analysis at the end of the pipeline

### ISSUE THREAD

**Issue by sebhoerl** [eqasim-org/ile-de-france#11]
Currently, as part of how the pipeline was developed, we compare intermediate results (e.g. the population after home and work location assignment) with reference data (e.g. the OD flows). However, it would be better and more versatile if we would only base the comparison on the final output. This would make it easier to replace and adapt algorithms, and set up proper unit tests.

**Comment by Nitnelav** [comment]
Fixed in https://github.com/eqasim-org/ile-de-france/pull/252
