### ISSUE TITLE
Update data to 2019

### ISSUE THREAD

**Issue by sebhoerl** [eqasim-org/ile-de-france#112]
Census data is available for 2018, it should be updated.

**Comment by ainar** [comment]
Census data is now available for 2019. We should check if this new version is compatible with the current code.

Hint for everyone to look for the last version of the census data: https://www.insee.fr/fr/information/2008354 will always point to the last census available. You still need to search there for each dataset.

The datasets from the census needed are:
- ***Individus localisés au canton-ou-ville*** ("Census data [RP]")
- ***Mobilités professionnelles des individus : déplacements commune de résidence / commune de travail*** ("Origin-destination data [RP-MOBPRO]")
- ***Mobilités scolaires des individus : déplacements commune de résidence / commune de scolarisation*** ("Origin-destination data [RP-MOBSCO]")
- ***Recensement de la population - Base infracommunale (IRIS)*** ("Population totals")

**Comment by sebhoerl** [comment]
Hi, if you want to have a look at that, I'd be happy to. I'll just let you know that I didn't tackle this task yet, because I expect it to be somewhat time-consuming. I'm almost sure that just replacing the data set will not work. The main concern I have is the zoning system. The IRIS change from year to year because there are splits and mergers of municipalities. See [ile-de-france](https://github.com/eqasim-org/ile-de-france)/[data](https://github.com/eqasim-org/ile-de-france/tree/develop/data)/[spatial](https://github.com/eqasim-org/ile-de-france/tree/develop/data/spatial)/code_changes.py for a stage that already processes this information, which is, fortunately, available in a structured way from INSEE. Right now we are using this somewhere (in the BPE I think) to retrofit the IRIS and municipalities to the 2017 IRIS shape file, which is used in most places and on which the 2015 RP is based on. This would need to be taken into account in other stages then, I think. For instance, you didn't mention the Filosofi data set for the incomes, which is also updated (and in the current version based on 2017 IRIS, I think), this would need to be updated or retrofitted then.

Ideally, the steps are:
- Find the latest version of all data sets
- Check IRIS system / date of municipality codes of the updated data sets
- Check if there is a common version that can be used
- For others, need to retrofit the identifiers to one reference system (here, the latest available IRIS definition from 2021 (or maybe even 2022?) would make sense)

**Comment by sebhoerl** [comment]
Of course one early fix would simply be to integrate the latest code translation database from INSEE, then integrate the 2019 RP, and add the code that translates the most recent codes (from RP 2019) back to the default IRIS 2017. Maybe this would be the easiest first step towards a more flexible system. 

Then we could apply the same logic to other data sets and updates would be easier in the future. Each stage that loads the raw information / cleans them would then need to have a step to check if all the municipalities / IRIS in the data are found in the current spatial identifiers or can be translated.
