### ISSUE TITLE
Clarify the generalizability of the synthesis

### ISSUE THREAD

**Issue by ainar** [eqasim-org/ile-de-france#135]
Hello,

This repository contains code to generate a synthetic population for any department in France effortlessly. This software is a more outstanding scientific contribution than just a population synthesis for Île-de-France.
Why not make it clear by, for instance, changing the repository's and environment's names with "synthetic_population"?
This clarification seems a mandatory passage for the sustainability of this repository.

Alongside the coherence of the naming of this tool, it would be easier for other people working with it. For example, if they work in different geographical areas, they can keep coherence in their work without the need to fork the repository and change the environment name.

Thank you for your work,

Aina

**Comment by Nitnelav** [comment]
I vote :    **eqasim-france**

**Comment by sebhoerl** [comment]
Okay, this is coming up frequently. I always do some maintenance of the repository around Christmas. So I guess this will be this year's project :) Plus moving the eqasim-java code here as well to simplify testing etc.

**Comment by ainar** [comment]
General issue here: https://github.com/eqasim-org/ile-de-france/issues/139
