### ISSUE TITLE
Value Error for categorieJuridiqueUniteLegale in sirene

### ISSUE THREAD

**Issue by kensongzhu** [eqasim-org/ile-de-france#146]
With latest **StockUniteLegale_utf8.zip**,  it fails when parsing **categorieJuridiqueUniteLegale** in [data/sirene/raw_siren.py](https://github.com/eqasim-org/ile-de-france/blob/15d8c2b533b2cf5f6f2258929e8eb0102ce656d0/data/sirene/raw_siren.py#L23).

```shell
...
ValueError: Integer column has NA values in column 27
...
```

From the definition [https://www.sirene.fr/sirene/public/variable/categorieJuridiqueUniteLegale](https://www.sirene.fr/sirene/public/variable/categorieJuridiqueUniteLegale)

It seems that its value can be null for purged units, and  it can be the case `0000` as well.   
Maybe we'd better just leave it as `str` instead of `int` ?

**Comment by sebhoerl** [comment]
Yes, I guess that should be fine. I'm not sure if we are even using `law_status` anywhere in the pipeline currently. I think we were extracting it to create B2B logistics flows, but this code is not yet in the repository.
