### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by Nasheor** [eqasim-org/ile-de-france#148]
Hey, 

I've been following the tutorials in population.md file and I am getting the population generated. However, I'm trying to understand the process in detail to replicate the pipeline and create a scenario for Ireland. 

For that, I'm playing around with the 'tests' in the ile-de-france repo. I run 'testdata.py'  with 'output'  as the parameter for the output folder. However,  I get a FileNotFoundError in line 680:
--write-pbf", "%s/osm/ile-de-france-220101.osm.pbf" % output_path

All other files prior to line 680 have been created. Is there something I'm missing? Any help would be much appreciated. 

Thanks

**Comment by sebhoerl** [comment]
Hi Nasheor, normally everything should work. Whenever a commit is made to this repository, the CI pipeline is started and all the tests are run. 

But if I understand correctly, you are trying to run `testdata.py`. Not sure if this should actually work. The `testdata` module is only used as a dependency and called from the unit tests. You can check in those tests how the directory and everything is prepared properly, maybe there is some folder missing or something like that in your setup.

**Comment by sebhoerl** [comment]
(That being said, you can run the tests by starting `pytest tests/`)

**Comment by sebhoerl** [comment]
Looking back at it, I think the problem is simply that the `osm` folder in the output folder does not exist in your case.
