### ISSUE TITLE
def define_distance_ordering 

### ISSUE THREAD

**Issue by neda-git** [eqasim-org/ile-de-france#156]
Hi @sebhoerl , when i run the pipeline, there is a problem in def define_distance_ordering in location.py, it returns this error :

 distances = np.sqrt(np.sum((commute_coordinates[f_available] - home_coordinate)**2, axis = 1))

TypeError: unsupported operand type(s) for -: 'float' and 'Point'

**Comment by sebhoerl** [comment]
For which use case do you have the error?

**Comment by neda-git** [comment]
I want to create the output population, I tried both data-sets ile-de-france and Toulouse / Occitanie and each time I got this error.

(venv) sh-5.1$ python3 -m synpp

INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:synpp:Found 46 stages
INFO:synpp:Found pipeline metadata in /home/nedam/ile-de-france/cache/pipeline.json
INFO:synpp:Devalidating 4 stages:
INFO:synpp:- synthesis.population.spatial.primary.locations__71edf7f15594b13dfe0155d93f3c1c06
INFO:synpp:- synthesis.output__f4813600e7ceb3691b35190213c4148e
INFO:synpp:- synthesis.population.spatial.secondary.locations__77081219cb1c795b149873c3276263ad
INFO:synpp:- synthesis.population.spatial.locations__77081219cb1c795b149873c3276263ad
INFO:synpp:Successfully reset meta data
INFO:synpp:Executing stage synthesis.population.spatial.primary.locations__71edf7f15594b13dfe0155d93f3c1c06 ...
INFO:synpp:Loading cache for synthesis.population.spatial.primary.candidates__71edf7f15594b13dfe0155d93f3c1c06 ...
INFO:synpp:Loading cache for synthesis.population.spatial.home.locations__faf67e2faca17f45baef7de45c600a15 ...
INFO:synpp:Loading cache for synthesis.population.spatial.commute_distance__f8d37f282cc1b07db3dc45fe779bae52 ...
INFO:synpp:Loading cache for synthesis.locations.work__f1f8f7ef4959c2179c2588ad069acd1e ...
INFO:synpp:Loading cache for synthesis.locations.education__2b85acf218218baec7e12dad4000777e ...
[[ 585453.15 6207390.39]]
[[ 586181.17 6207773.88]
 [ 598555.16 6185544.33]]
[[ 585714.07942901 6208057.51345551]
 [ 604441.08504045 6181131.22362344]]
[[ 585699.94       6208024.11      ]
 [ 586311.95       6207114.42      ]
 [ 586673.435      6224555.12      ]
 [ 586584.85       6225137.1       ]
 [ 587858.59       6224587.65      ]
 [ 587772.1        6223459.1       ]
 [ 586823.4304488  6224749.14562528]
 [ 586878.297      6224978.76      ]]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/nedam/ile-de-france/venv/lib/python3.10/site-packages/synpp/parallel.py", line 38, in pipeline_runner
    return callable(pipeline_parallel_context, args)
  File "/home/nedam/ile-de-france/synthesis/population/spatial/primary/locations.py", line 60, in process_municipality
    indices = define_ordering(df_persons, df_candidates, context.progress)
  File "/home/nedam/ile-de-france/synthesis/population/spatial/primary/locations.py", line 27, in define_distance_ordering
    distances = np.sqrt(np.sum((commute_coordinates[f_available] - home_coordinate)**2, axis = 1))
TypeError: unsupported operand type(s) for -: 'float' and 'Point'
"""

**Comment by sebhoerl** [comment]
Are you sure you are using the current `develop` branch or a fixed version? Those lines with the numbers lool like some debugging output.

**Comment by sebhoerl** [comment]
Also, I see that you are in a `venv`, maybe you have not installed the right dependencies? This repository comes with a conda/mamba environment configuration file.

**Comment by neda-git** [comment]
I'm using the current develop branch. I will check all dependencies perhaps i did something wrong. Thank you for taking me time.

**Comment by sebhoerl** [comment]
From the other issue, I understand that it worked?

**Comment by neda-git** [comment]
As you mentioned, the problem for the synthetic population was related to the conda environment, so it solved. Now, for the simulation i get the errors but as you told me java should be set to Java11. I will try that. Thanks
