### ISSUE TITLE
"Unable to load cache item" tests error when running the simulation

### ISSUE THREAD

**Issue by caviri** [eqasim-org/ile-de-france#157]
Hello, 

I successfully generated the synthetic dataset following the first tutorial. However, when I tried to run the simulation (second tutorial), there were four failing tests. 

```
Results :

Tests in error: 
  testTwoOrdinaryTours(org.eqasim.mode_choice.TestSpecialModeChoiceCases): java.lang.IllegalStateException: Unable to load cache item
  testOrdinaryTour(org.eqasim.mode_choice.TestSpecialModeChoiceCases): java.lang.IllegalStateException: Unable to load cache item
  testTails(org.eqasim.mode_choice.TestSpecialModeChoiceCases): java.lang.IllegalStateException: Unable to load cache item
  testFreeChain(org.eqasim.mode_choice.TestSpecialModeChoiceCases): java.lang.IllegalStateException: Unable to load cache item

Tests run: 13, Failures: 0, Errors: 4, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for eqasim 1.3.1:
[INFO] 
[INFO] eqasim ............................................. SUCCESS [01:30 min]
[INFO] core ............................................... FAILURE [ 14.522 s]
[INFO] ile_de_france ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:46 min
[INFO] Finished at: 2023-02-22T11:08:50+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project core: There are test failures.

```
I am running this on an M1 Pro with the following versions:

**JAVA**
```
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode)
```

**MAVEN**
```
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /Users/carlosvivarrios/pro/digital_twin/iledefrance/apache-maven-3.8.7
Java version: 17.0.6, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
Default locale: en_CH, platform encoding: UTF-8
OS name: "mac os x", version: "13.2", arch: "aarch64", family: "mac"
```

Could this error be due to a version incompatibility? Which versions of JDK and Maven are being used for testing?

Thanks!

**Comment by sebhoerl** [comment]
Hi, in the CI we still use `jdk8u252-b09` and Maven 3.6.3, you could try with that:
https://github.com/eqasim-org/ile-de-france/blob/develop/.github/workflows/tests.yml

But when we run the simulations on our servers, we also use 17. 

Do you have more log output on top of that, maybe with the whole stack trace of the error message?

**Comment by caviri** [comment]
Hi Sebastian, I tried 3.6.3 + Java17, and the same issue persists. I'll try to use jdk8. 

The total error log is too long to be pasted but here you have the beginning and the end. (+ you can find the total one attached [errorlog.txt](https://github.com/eqasim-org/ile-de-france/files/10803611/errorlog.txt)): 

**Beginning**
```
(ile-de-france) carlosvivarrios@IC-SDSC-LMC33 ile-de-france % python3 -m synpp               
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
SQLalchemy is not installed. No support for SQL output.
INFO:synpp:Found 63 stages
INFO:synpp:Found pipeline metadata in /Users/carlosvivarrios/pro/digital_twin/iledefrance/cache/pipeline.json
WARNING! A Java JDK of at least version 11 is recommended.
INFO:synpp:Devalidating 15 stages:
INFO:synpp:- matsim.runtime.eqasim__357afece02b6584929b863386975b349
INFO:synpp:- matsim.simulation.prepare__f929da6cc176dd61e6b2b8ee67040f88
INFO:synpp:- matsim.runtime.pt2matsim__9691b05d75a08f1624b6cf94818fe35a
INFO:synpp:- matsim.scenario.supply.osm__aef4c7a99ed862be29db6cee50d58e32
INFO:synpp:- data.gtfs.cleaned__23f375cc8001656baaadbaead38ca96d
INFO:synpp:- matsim.scenario.supply.gtfs__d381c00b289b903177386b07126d3e79
INFO:synpp:- data.osm.cleaned__eb0db514680855138cd3185cc50eedfd
INFO:synpp:- matsim.output__92653a99279641e4ac36a6aede53aea8
INFO:synpp:- data.spatial.departments__69bb5b867e80f7d6ea44d99678722814
INFO:synpp:- matsim.simulation.run__f929da6cc176dd61e6b2b8ee67040f88
INFO:synpp:- matsim.scenario.facilities__32cec8c565e96ba422aaa7833db73115
INFO:synpp:- matsim.scenario.supply.processed__a86772c51e850005d9a71d3e7da075c3
INFO:synpp:- matsim.scenario.population__3f09435799188b789c125928292988da
INFO:synpp:- synthesis.output__21eb7cd87b4c2281d7f599197fbb97b6
INFO:synpp:- matsim.scenario.households__8d9b779f9c3c6701d1e0c6d5f33b1a9d
INFO:synpp:Successfully reset meta data
INFO:synpp:Executing stage matsim.runtime.eqasim__357afece02b6584929b863386975b349 ...
INFO:synpp:Loading cache for matsim.runtime.git__ad41c38f3c0edd3fc8d31fcf4b034657 ...
Cloning into 'eqasim-java'...
remote: Enumerating objects: 593, done.
remote: Counting objects: 100% (593/593), done.
remote: Compressing objects: 100% (442/442), done.
remote: Total 593 (delta 150), reused 372 (delta 85), pack-reused 0
Receiving objects: 100% (593/593), 4.51 MiB | 11.56 MiB/s, done.
Resolving deltas: 100% (150/150), done.
INFO:synpp:Loading cache for matsim.runtime.maven__ef36d138ba5a7974a09d2a4d0e1e77a4 ...
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.eqasim:core:jar:1.3.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ org.eqasim:eqasim:1.3.1, /Users/carlosvivarrios/pro/digital_twin/iledefrance/cache/matsim.runtime.eqasim__357afece02b6584929b863386975b349.cache/eqasim-java/pom.xml, line 118, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.eqasim:switzerland:jar:1.3.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ org.eqasim:eqasim:1.3.1, /Users/carlosvivarrios/pro/digital_twin/iledefrance/cache/matsim.runtime.eqasim__357afece02b6584929b863386975b349.cache/eqasim-java/pom.xml, line 118, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.eqasim:ile_de_france:jar:1.3.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ org.eqasim:eqasim:1.3.1, /Users/carlosvivarrios/pro/digital_twin/iledefrance/cache/matsim.runtime.eqasim__357afece02b6584929b863386975b349.cache/eqasim-java/pom.xml, line 118, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.eqasim:sao_paulo:jar:1.3.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ org.eqasim:eqasim:1.3.1, /Users/carlosvivarrios/pro/digital_twin/iledefrance/cache/matsim.runtime.eqasim__357afece02b6584929b863386975b349.cache/eqasim-java/pom.xml, line 118, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.eqasim:examples:jar:1.3.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ org.eqasim:eqasim:1.3.1, /Users/carlosvivarrios/pro/digital_twin/iledefrance/cache/matsim.runtime.eqasim__357afece02b6584929b863386975b349.cache/eqasim-java/pom.xml, line 118, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.eqasim:san_francisco:jar:1.3.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ org.eqasim:eqasim:1.3.1, /Users/carlosvivarrios/pro/digital_twin/iledefrance/cache/matsim.runtime.eqasim__357afece02b6584929b863386975b349.cache/eqasim-java/pom.xml, line 118, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.eqasim:los_angeles:jar:1.3.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ org.eqasim:eqasim:1.3.1, /Users/carlosvivarrios/pro/digital_twin/iledefrance/cache/matsim.runtime.eqasim__357afece02b6584929b863386975b349.cache/eqasim-java/pom.xml, line 118, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.eqasim:vdf:jar:1.3.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ org.eqasim:eqasim:1.3.1, /Users/carlosvivarrios/pro/digital_twin/iledefrance/cache/matsim.runtime.eqasim__357afece02b6584929b863386975b349.cache/eqasim-java/pom.xml, line 118, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.eqasim:eqasim:pom:1.3.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 118, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

**End**
```
Results :

Tests in error: 
  testTwoOrdinaryTours(org.eqasim.mode_choice.TestSpecialModeChoiceCases): java.lang.IllegalStateException: Unable to load cache item
  testOrdinaryTour(org.eqasim.mode_choice.TestSpecialModeChoiceCases): java.lang.IllegalStateException: Unable to load cache item
  testTails(org.eqasim.mode_choice.TestSpecialModeChoiceCases): java.lang.IllegalStateException: Unable to load cache item
  testFreeChain(org.eqasim.mode_choice.TestSpecialModeChoiceCases): java.lang.IllegalStateException: Unable to load cache item

Tests run: 13, Failures: 0, Errors: 4, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for eqasim 1.3.1:
[INFO] 
[INFO] eqasim ............................................. SUCCESS [  0.479 s]
[INFO] core ............................................... FAILURE [  8.619 s]
[INFO] ile_de_france ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.229 s
[INFO] Finished at: 2023-02-22T13:17:33+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project core: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/carlosvivarrios/pro/digital_twin/iledefrance/cache/matsim.runtime.eqasim__357afece02b6584929b863386975b349.cache/eqasim-java/core/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :core
Traceback (most recent call last):
  File "/Users/carlosvivarrios/opt/anaconda3/envs/ile-de-france/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/carlosvivarrios/opt/anaconda3/envs/ile-de-france/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/carlosvivarrios/opt/anaconda3/envs/ile-de-france/lib/python3.7/site-packages/synpp/__main__.py", line 14, in <module>
    synpp.run_from_yaml(config_path)
  File "/Users/carlosvivarrios/opt/anaconda3/envs/ile-de-france/lib/python3.7/site-packages/synpp/pipeline.py", line 803, in run_from_yaml
    run(definitions=definitions, config=config, working_directory=working_directory, flowchart_path=flowchart_path, dryrun=dryrun)
  File "/Users/carlosvivarrios/opt/anaconda3/envs/ile-de-france/lib/python3.7/site-packages/synpp/pipeline.py", line 713, in run
    result = stage["wrapper"].execute(context)
  File "/Users/carlosvivarrios/opt/anaconda3/envs/ile-de-france/lib/python3.7/site-packages/synpp/pipeline.py", line 59, in execute
    return self.instance.execute(context)
  File "/Users/carlosvivarrios/pro/digital_twin/iledefrance/ile-de-france/matsim/runtime/eqasim.py", line 43, in execute
    maven.run(context, ["-Pstandalone", "--projects", "ile_de_france", "--also-make", "package"], cwd = "%s/eqasim-java" % context.path())
  File "/Users/carlosvivarrios/pro/digital_twin/iledefrance/ile-de-france/matsim/runtime/maven.py", line 34, in run
    return_code = sp.check_call(command_line, cwd = cwd)
  File "/Users/carlosvivarrios/opt/anaconda3/envs/ile-de-france/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/carlosvivarrios/pro/digital_twin/iledefrance/apache-maven-3.6.3/bin/mvn', '-Djava.io.tmpdir=/Users/carlosvivarrios/pro/digital_twin/iledefrance/cache/matsim.runtime.eqasim__357afece02b6584929b863386975b349.cache/__java_temp', '-Pstandalone', '--projects', 'ile_de_france', '--also-make', 'package']' returned non-zero exit status 1.
```

**Comment by sebhoerl** [comment]
I think the key is this here in the log:

> INFO: An exception was caught and reported. Message: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @7fac631b
java.lang.IllegalStateException: Unable to load cache item

There are quite some hits on `module java.base does not "opens java.lang" to unnamed module` with links to the JDK version, e.g. https://stackoverflow.com/questions/67782975/how-to-fix-the-module-java-base-does-not-opens-java-io-to-unnamed-module

So I guess using an older JDK will help. And we'll upgrade in https://github.com/eqasim-org/eqasim-java asap ;-)

**Comment by neda-git** [comment]
Hello @sebhoerl, 
In running the simulation part i got this error:

[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ core ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 158 source files to /home/nedam/PycharmProjects/ile-de-france2/cache/matsim.runtime.eqasim__97300124d453f91c1f5b3f4615ebe5da.cache/eqasim-java/core/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for eqasim 1.3.1:
[INFO] 
[INFO] eqasim ............................................. SUCCESS [01:31 min]
[INFO] core ............................................... FAILURE [  2.338 s]
[INFO] ile_de_france ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:37 min
[INFO] Finished at: 2023-02-24T13:22:21+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project core: Fatal error compiling: invalid target release: 11 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :core
Traceback (most recent call last):
  File "/home/nedam/anaconda3/envs/ile-de-france/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nedam/anaconda3/envs/ile-de-france/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nedam/anaconda3/envs/ile-de-france/lib/python3.7/site-packages/synpp/__main__.py", line 14, in <module>
    synpp.run_from_yaml(config_path)
  File "/home/nedam/anaconda3/envs/ile-de-france/lib/python3.7/site-packages/synpp/pipeline.py", line 886, in run_from_yaml
    Synpp.build_from_yml(path).run_pipeline()
  File "/home/nedam/anaconda3/envs/ile-de-france/lib/python3.7/site-packages/synpp/pipeline.py", line 912, in run_pipeline
    ensure_working_directory=True, externals=self.externals, aliases=self.aliases)
  File "/home/nedam/anaconda3/envs/ile-de-france/lib/python3.7/site-packages/synpp/pipeline.py", line 810, in run
    result = stage["wrapper"].execute(context)
  File "/home/nedam/anaconda3/envs/ile-de-france/lib/python3.7/site-packages/synpp/pipeline.py", line 88, in execute
    return self.instance.execute(context)
  File "/home/nedam/PycharmProjects/ile-de-france2/matsim/runtime/eqasim.py", line 43, in execute
    maven.run(context, ["-Pstandalone", "--projects", "ile_de_france", "--also-make", "package"], cwd = "%s/eqasim-java" % context.path())
  File "/home/nedam/PycharmProjects/ile-de-france2/matsim/runtime/maven.py", line 34, in run
    return_code = sp.check_call(command_line, cwd = cwd)
  File "/home/nedam/anaconda3/envs/ile-de-france/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/nedam/apache-maven-3.6.3/bin/mvn', '-Djava.io.tmpdir=/home/nedam/PycharmProjects/ile-de-france2/cache/matsim.runtime.eqasim__97300124d453f91c1f5b3f4615ebe5da.cache/__java_temp', '-Pstandalone', '--projects', 'ile_de_france', '--also-make', 'package']' returned non-zero exit status 1.
------------------------------------------------------------------------------------------------------------------------------------
I'm running with the following versions:

**Java**
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)

**Maven**
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/nedam/apache-maven-3.6.3
Java version: 1.8.0_252, vendor: AdoptOpenJDK, runtime: /home/nedam/jdk8u252-b09/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.0.12-76060006-generic", arch: "amd64", family: "unix"

Thank you in advance

**Comment by sebhoerl** [comment]
Ok, now the relevant error is clearly this:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project core: Fatal error compiling: invalid target release: 11 -> [Help 1]

Because in the eqasim-java repository we need Java 11. On the other hand, the CI script here in this repository clearly uses JDK 8. I think it will definitely work if you use a Adoptium Java 11 release. But still weird why it works here ... I'll investigate on that.

**Comment by sebhoerl** [comment]
Ah, I found the issue. Actually, the CI seems to use a default Java from Github and not the one that is installed manually. So it is actually using Java 11:
![image](https://user-images.githubusercontent.com/647500/221257377-179d747f-e3ff-46ad-bb09-8f63ee1987cf.png)

**Comment by neda-git** [comment]
Hi @sebhoerl , the simulation worked perfectly. Thank you.

**Comment by caviri** [comment]
Hi, @sebhoerl Thanks for checking this. I'll try to run the whole pipeline in a docker container using Java 11.

**Comment by sebhoerl** [comment]
Great, I was updating the CI workflow on Github to better reflect the environment that is necessary :)
