### ISSUE TITLE
How to perform down to commune level ?

### ISSUE THREAD

**Issue by kensongzhu** [eqasim-org/ile-de-france#165]
Hi, 

I want to do a case study on commune Marseille, 
As far as I see, the simulation is only on department level, right? 

I tried to extend the config with `communes` 

```yaml
  census_path: rp_2019/FD_INDCVIZE_2019.csv
  bdtopo_path: bdtopo_marseille/BATIMENT.shp
  regions: [ 93 ]
  departments: [ 13 ]
  communes: [
    13201, 13202, 13203, 13204, 13205, 13206, 13207,
    13208, 13209, 13210, 13211, 13212, 13213, 13214,
    13215, 13216
  ]
```

Then I modified `data/spatial/codes.py` by filttering the given communes ids from the extended config

But somehow I get the error

```
    return self.instance.execute(context)
  File "/home/xxx/ile-de-france/data/census/cleaned.py", line 56, in execute
    raise RuntimeError("Found additional communes: %s" % excess_communes)
RuntimeError: Found additional communes: {'13005', '13104', '13056', '13027', '13001', '13015', '13075', '13063', '13041', '13021', '13043', '13071', '13086', '13002', '13106', '13092', '13107', '13097', '13022', '13113', '13040', '13102', '13014', '13042', '13028', '13105', '13110', '13039', '13108', '13117', '13119', '13019', '13054', '13069', '13051', '13047', '13032', '13007', '13100', '13103', '13050', '13035', '13112', '13026', '13081', '13098', '13004', '13078', '13077', '13070', '13037', 'undefined'}
```

Is this the right way to do so if I want to downscale to commune?  if so, am I  missing anything here?

**Comment by kensongzhu** [comment]
@Nitnelav Thank you for the quick response.

One thing I am not sure here is the `sampling_rate`, that is for region level right ? How to acchieve that when I want to explicitly specify 10% on commute level. Does the `RunScenarioCutter` cover this?

**Comment by sebhoerl** [comment]
The sampling rate is based on households, if you set 10%, the pipeline will generate only 10% of the real amount of households, but they will still be distributed realistically (proportionally) on the whole territory. You'll always have side effects from people going in and out of the study area when you perform a simulation, so it makes sense to simulate a larger area. Usually we simply select the departments, this makes most sense with how the data in France is structured.

If you only want to do analyses based on the synthetic population (without a MATSim) simulation, you can simply run the department and then filter out agents by home location in the output data (easiest is through `homes.gpkg`). If you run a MATSim simulation, as said, it might make sense to simulate the whole department to avoid border effects. Alternatively, you could simply do the same filtering using `homes.gpkg` and remove those households that don't live in your study area (defined by your municipalities) - you'd just need to remove those agents from the `population.xml.gz` that you have filtered out.
