### ISSUE TITLE
Adding other pollutants to RunEXportEmissionNetwork

### ISSUE THREAD

**Issue by neda-git** [eqasim-org/ile-de-france#190]
Hi @Nitnelav, I would like to have the emission.shp for the other polluants like NO2, SO2 and PM2_5, in RunEXportEmissionNetwork I want to add these three emissions too, I forked the repo and edited the file but I don't know what else i should do to using this commandline for running: 
java -cp ile_de_france-1.0.6.jar org.eqasim.ile_de_france.emissions.RunExportEmissionsNetwork --config-path config.xml --time-bin-size 3600

Thank you in advance

**Comment by sebhoerl** [comment]
Closing this now, please reopen if it is still an issue.
