### ISSUE TITLE
Error about pathway & file not existing 

### ISSUE THREAD

**Issue by BaptisteLeroux** [eqasim-org/ile-de-france#207]
When I run python -m synpp, I had those errors : 
![image](https://github.com/eqasim-org/ile-de-france/assets/76404701/9bd4d2a3-b4de-4899-b42d-b622f05dd0f4)
This is due to unzipping issue. Do it manually in the data folder. 
Then you will face another error due to pathway which should be automaticaly correct. However it does not found the right one. 
One solution is to modify directly the files iris.py and raw.py (spatial and bdtopo folders). 
Here is an exampleof what I did with my own path :

[data.zip](https://github.com/eqasim-org/ile-de-france/files/13658530/data.zip)

**Comment by sebhoerl** [comment]
Well, modifying the paths manually is not really a solution ;)

So it seems that there is an error in 7z? What happens if you just try to unzip the file using the 7z package via a notebook or a simple script? Can you reproduce the problem?

**Comment by BaptisteLeroux** [comment]
![image](https://github.com/eqasim-org/ile-de-france/assets/76404701/250948c5-8fe3-4846-89a6-9f997ca1372e)
This part is working when the notebook file is in the iris_2021 directory in data

**Comment by sebhoerl** [comment]
Ok, so here you don't get the error when `archive.extract` is called, this is where the error happens in the first case.

You say that you execut that in the directoy where the 7z is located. What happens if you execute this anywhere also and you give the full absolute path `C:\\...` to `SevenZipFile`? I have a doubt that the path is simply too long to be handled by Windows.

**Comment by BaptisteLeroux** [comment]
![image](https://github.com/eqasim-org/ile-de-france/assets/76404701/2c34106a-73d4-46eb-8fbe-3820edfd5f23)
This works, it's just necessaray to add the "\\" instead of single "\" in the path tho. If I only copy paste the absolute path from my folder without doubling each "\" it reports a unicode error

**Comment by BaptisteLeroux** [comment]
![image](https://github.com/eqasim-org/ile-de-france/assets/76404701/9d2f5888-931f-45b6-89cc-1b7f04a1872a)
Here it's also working when i put in the extract function

**Comment by sebhoerl** [comment]
Hm, ok, but here the paths are still shorter than before. Does it work if you put the absolute paths that are used inside the pipeline (wit the cache paths etc)?

**Comment by sebhoerl** [comment]
Please reopen if the problem has not been resolved.
