### ISSUE TITLE
"Municipality Filosofi data is not available"

### ISSUE THREAD

**Issue by Jrmwelli** [eqasim-org/ile-de-france#250]
I'm sorry, I have an issue I don't understand and maybe you can help
I followed every steps to have the same exact folder structure than presented in "population.md"
When I try to run "python -m synpp" (because I'm using Windows), I have this error :
<img width="694" alt="image" src="https://github.com/user-attachments/assets/98386a73-5928-4df3-9387-7dae32fd10df">
I've changed "data_path" in config.yml to the folder where I've stored the data (So now it's C:\Users\JeromeGARCIA\Memoire\data)
I'm not sure what I've done wrong. The error always involved "Municipality Filosofi data" every time I try to run it. 
If you know what I can do about it I'll be really interested ! Thanks !

**Comment by balacmi** [comment]
Hi @Jrmwelli, Could you please share the folder structure?

**Comment by Jrmwelli** [comment]
Hi @balacmi, of course !
I put the folder tree into this .txt
[structure.txt](https://github.com/user-attachments/files/16410638/structure.txt)
All these files are in "C:\Users\[MyName]\Memoire", with two folders :
- code (where I've cloned the repository)
- data (where I've stored the required data)
ban_ara and bdtopo_ara are here because I've also stored the data for Lyon's region
Thanks for your help !

**Comment by balacmi** [comment]
You have a typo ;) : `filisofi_2019` instead of `filosofi_2019 `

**Comment by Jrmwelli** [comment]
Oh I'm really sorry I didn't intend to waste your time
I will correct this immediately, thanks a lot for your help !
