### ISSUE TITLE
Synthesis.locations.home.locations is not a supported object for pipeline stage definition!

### ISSUE THREAD

**Issue by diallitoz** [eqasim-org/ile-de-france#253]
Hi,

I am trying to use the new version of the pipeline to generate synthttic population.

I got the following error 
File "/work/home/.conda/envs/ile-de-france_v2/lib/python3.10/site-packages/synpp/pipeline.py", line 418, in process_stages
    raise PipelineError(f"{definition['descriptor']} is not a supported object for pipeline stage definition!")
synpp.general.PipelineError: synthesis.locations.home.locations is not a supported object for pipeline stage definition!

Any idea?

Best

**Comment by vincent-leblond** [comment]
Hi,
I don't have much idea. However you may start by making sure that you have the correction python package version : reinstall the conda environment.

**Comment by diallitoz** [comment]
> Hi, I don't have much idea. However you may start by making sure that you have the correction python package version : reinstall the conda environment.

Thanks for your answer.
Ok I will reinstall my virtual environment.
It is still curious that the other stages run perfectly that it is the one that does not pass.

**Comment by diallitoz** [comment]
> Hi, I don't have much idea. However you may start by making sure that you have the correction python package version : reinstall the conda environment.



> > Hi, I don't have much idea. However you may start by making sure that you have the correction python package version : reinstall the conda environment.
> 
> Thanks for your answer. Ok I will reinstall my virtual environment. It is still curious that the other stages run perfectly that it is the one that does not pass.

Finally, I cloned the project again and relaunched the pipeline directly in the cloned folder. Everything ran fine this time.

Before, I had not used the cloned project but copied the new data into an old repo to have the current version of the pipeline. Maybe that's where the bug comes from.

Thanks again Vincent!

**Comment by sebhoerl** [comment]
I noticed that some people put the input files into the `data` folder of the cloned repository, is this what you did? Maybe we should clarify somewhere in the documentation that this is not the idea, but the point is to separate the cloned repository completely from the data and have the data in a separate folder. :)

**Comment by diallitoz** [comment]
> I noticed that some people put the input files into the `data` folder of the cloned repository, is this what you did? Maybe we should clarify somewhere in the documentation that this is not the idea, but the point is to separate the cloned repository completely from the data and have the data in a separate folder. :)

I put the input files in a different folder than the cloned repo.
It is indeed good to specify it to avoid confusion. :)
