### ISSUE TITLE
Cannot create conda env

### ISSUE THREAD

**Issue by JusteRaimbault** [eqasim-org/ile-de-france#52]
When trying to run `conda env create -f environment.yml` I get the following error:

```UnsatisfiableError: The following specifications were found to be in conflict:
  - geopandas 0.6.1*
  - numba 0.49.0* -> llvmlite >=0.32.0
  - shapely 1.7.0*
 ```

[Mac OSX 10.15.5; Python 3.6.2 :: Anaconda 4.4.0 (x86_64)]

**Comment by sebhoerl** [comment]
Hi, I just tried to create a new environment from scratch and it seems to work. I notice that I have `conda 4.8.3`, maybe try to update? I'm running on Linux, also the unit tests run on linux, so it might also be a OSX problem.

**Comment by JusteRaimbault** [comment]
Thanks for the prompt reply ! Sorry I did not paste the full issue - it was saying something about incompatibilities in dependencies for the packages mentioned above - I updated conda to `conda 4.9.2` and it is working now; this may be linked to OSX, I was also having issues with the correct python/pip/conda being called (python is still a nightmare on mac).
The pipeline is running now, closing this.
