### ISSUE TITLE
Instructions need an update

### ISSUE THREAD

**Issue by ClarissaLiv** [eqasim-org/ile-de-france#72]
step 10 needs to be updated. 

a) it seems only Mars 2021 is available, and no longer Décembre 2020
b) the archive is difficult to download using a normal browser (Chrome asks for an App....not sure which one would understand that .7z is a file to download, not an application to open nor a website to go to...). This is the same problem that the other step with the greoservices.ign.fr has, I think.

**Comment by balacmi** [comment]
Thanks Clarissa.
a) yes that should be updated
b) they say at the start of the page that most browsers will not be able to download the data anymore, so one needs to use a ftp client

**Comment by ClarissaLiv** [comment]
just did
