### ISSUE TITLE
Could we make a list of tips

### ISSUE THREAD

**Issue by ClarissaLiv** [eqasim-org/ile-de-france#79]
For instance, how to use ftp for those who haven't before. It would save people time.

Or, for instance, some more detailed instructions on how to use this "osmosis_binary" option, since I've tried several version and it hasn't worked.

Advice on how to deal with making sure a system has the required things installed and callable (it's not always straightforward, especially on Linux servers....I figure we can spare others from this time suck by writing down what's worked for us....).

**Comment by ClarissaLiv** [comment]
Like, for instance, the phrase "make osmosis available from the command line" is super super vague for most people. 
To help most people, in the "tips" readme, we could write something like:

To make Osmosis available from the command line on a linux machine, do the following:

PATH=/full-path-to-osmosis/bin:$PATH <--- e.g. PATH=/drivename/username/osmosis/bin/:$PATH 
OSMOSIS_HOME=/full-path-to-osmosis/ <--- e.g. JAVA_HOME=/drivename/username/osmosis

**Comment by sebhoerl** [comment]
Hi Clarissa, I just enabled the Wiki for this repository. I think that could be a good place to go for this kind of information, and then it is a bit separate from the documentation (where we can put cross-links to the Wiki). What do you think? I think you should have access to create a first page in the Wiki. If not, let me know!

**Comment by ClarissaLiv** [comment]
I think this sounds perfect. :) I'll give editing the wiki a try.

**Comment by ClarissaLiv** [comment]
yes, it works nicely :) thanks!
