### ISSUE TITLE
Use BAN instead of BD-TOPO

### ISSUE THREAD

**Issue by sebhoerl** [eqasim-org/ile-de-france#94]
Instead of BD-TOPO for addresses, make use of the Base Adresse Nationale (BAN)
https://www.data.gouv.fr/fr/datasets/base-adresse-nationale/

**Comment by balacmi** [comment]
What is the difference?

**Comment by sebhoerl** [comment]
It is the new official thing to geocode addresses in France supported by the government, La Poste, IGN, and others. They even have an open source geocoder (Addok), but I think we cannot really use it as a library, it needs to be set up as a server. Still, BAN seems to be the better source now for address data (they also combine BD-TOPO with various more local address databases).

**Comment by sebhoerl** [comment]
And it will be easier to access for people, because we can simply put a link in the documentation and don't need to explain how to browse to the correct FTP folder or whatever :)

**Comment by balacmi** [comment]
Amazing!
