### ISSUE TITLE
Lyon: definition of socioprofessional class variable is not comparable between HTS and Census

### ISSUE THREAD

**Issue by ouassimm** [eqasim-org/ile-de-france#98]
https://github.com/eqasim-org/ile-de-france/blob/1e57fe52665953dff25b1a21e0953a91859adc56/synthesis/population/matched.py#L182

[In HTS](https://github.com/eqasim-org/ile-de-france/blob/1e57fe52665953dff25b1a21e0953a91859adc56/data/hts/edgt_lyon/cleaned_cerema.py#L178),  variable P9 is used to define the socioprofessional class. P9 describes in fact the occupational status (working or not). Instead of P9, we can use P11 with some category aggregation to match the census definition.

[In Census](https://github.com/eqasim-org/ile-de-france/blob/1e57fe52665953dff25b1a21e0953a91859adc56/data/census/cleaned.py#L105), variable CS1 describes the socioprofessional category as it should be. 

CS1 and P9 are not comparable. Matching HTS and Census assuming CS1 = P9 can bias the outcomes of matching.

**Comment by sebhoerl** [comment]
Ok, I see the problem, but I'm not even sure if we are talking about the same files. What do you get if you run `hts.data.output` as part of the pipeline? In `hts_persons.csv` I see values from 1 to 9 for the `socioprofessional_class`, but not just a binary "working or not". So something might be off here?

However, I just checked, and you're right. In my definition file, I have this:
![image](https://user-images.githubusercontent.com/647500/153472687-50035d95-84b7-460d-8860-a5737f1b6cc0.png)

And then in the dictionary: 
![image](https://user-images.githubusercontent.com/647500/153472818-63b6d964-bc86-480a-bce3-8207af730038.png)

So I'm not really sure what the column means in the end. You see `P9` is given explicitly in the dicionary, but in the list of variables they refer to `P11` in the description and in the last column. On the other hand, `P11` doesn't even exist in the list of variables. Not sure what to make out of this.

And in the dictionary, I have: `P12 POSSESSION D'UN ABONNEMENT TC HIER ` so in all other cases, the two last columns in the list of variables seem to describe what is actually in that field, while the initial column (with blue background) seems to be messed up. 

But the bottomline is that the EDGT actually doesn't contain a proper sociodemographic category, but some strange merger of different information. It's really a pity that there are standardized metrics but then they are not used... So if the dictionary from `P9` is used here, we have no chance, if `P11` is used, we can somehow construct a similar variable in the census, if we want, do I see that correctly?

The same problem, btw, seems to be in the EDGT for Nantes (the open data version). For the ADISP version of Lyon, @Nitnelav uses a field called `PCSC` which does not exist in these versions. Not sure if there we have the same problem?

**Comment by sebhoerl** [comment]
So the census (and ENTD and EGT) seem to refer to the PCS 2003, while the EDGT seems to refer to the PCS 1984 with additional categories: https://fr.wikipedia.org/wiki/Professions_et_cat%C3%A9gories_socioprofessionnelles_en_France

**Comment by sebhoerl** [comment]
So basically we can reconstuct the field `CS1` from the census using the information from EDGT (if we have the right columns) like that:
- Take the initial field `PCS` from the EDGT (9 values Agriculture -> Autre inactif)
- Set the field to 8 if `PCS > 6`
- Set the field to 7 if `OCCUPATION DE LA PERSONNE == RETRAITE`

Or am I wrong? :)

**Comment by ouassimm** [comment]
I have not checked the definition of P11 in the ENTD or EGT, but for any other EDGT survey (at least starting from 2015), here is the definition: 
![image](https://user-images.githubusercontent.com/35328756/153556968-6d9c7c63-289d-4e06-9002-66da822d280f.png)

As you can see, P11 describes the PCS but contains more details than CS1. Your screenshot (from the EGT if I'm not mistaken) shows a more aggregate definition of PCS (in 9 categories). 

Your solution should work for the EGT. For the EDGT, we can simply aggregate P11 by stripping P11 codes (for example 21 or 22 become 2):
|P11 id (EDGT)|Name|New PCS id to match CS1|
|----|----|-----|
|21 | Artisan |2|
|22 | Commerçant et assimilés| 2|
|23 | Chefs d’entreprise de 10 salariés ou plus| 2|

**Comment by sebhoerl** [comment]
No, the screenshots are exactly from the EDGT that I have received from CEREMA. That is why I'm wondering if we're even using the same files.

**Comment by sebhoerl** [comment]
But also in your screenshot for `PCS` something is strange, because it does not correspond to INSEE. 

Here are the official codes:
https://www.insee.fr/fr/information/2400059

In your screenshot, there is, for instance, a category `88`, but this one does not exist in INSEE.

**Comment by sebhoerl** [comment]
You mentioned above "any other EDGT survey". I have now at least 3 EDGT surveys that have different formats. Are you sure that they all should be the same? Maybe I always just got messed up data :D

**Comment by sebhoerl** [comment]
This is what is in the EDGT for Nantes, for instance. Here it is P9:
![image](https://user-images.githubusercontent.com/647500/153559828-6ae59fbe-9fc5-4aa6-9983-e9107faadf12.png)

**Comment by ouassimm** [comment]
Could not be more confusing... I'm using another variant of the Lyon's EDGT that might be different from the one produced by CEREMA. We've got these data as we were involved in the EDGT survey project. I wrongly assumed that our version was the same as the CEREMA's version. I'm no longer sure about EDGT data standardization...but I think that your version should be the standard one, at least for Lyon.

To sum up, in Nantes, the P9 variable describes the PCS as it should be. In Lyon (CEREMA version of EDGT = your version), P9 describes the occupational status (nothing to do with PCS) and P11 describes the PCS in 9 categories. Also in Lyon (LAET version of EDGT), P11 describes in detail the PCS (more than 9 categories).

For Lyon, your solution (https://github.com/eqasim-org/ile-de-france/issues/98#issuecomment-1035343575) should solve the problem for the CEREMA's version of the EDGT. It should do it for me as well.

**Comment by Nitnelav** [comment]
I can confirm that there are inconsistencies between various EDGT dictionnaries and neither of them strictly match the "official" EDGT definitions.
This is why we end up with seperate code for lyon and nantes, and even seperate code for lyon's EDGT from CEREMA and lyon's EDGT from ADISP.
@ouassimm is the LAET version different from the ADISP version ( http://www.progedo-adisp.fr/serie_emd.php ) ?

**Comment by sebhoerl** [comment]
Ok, here is a little analysis. For the EGT everything fits nicely:
![image](https://user-images.githubusercontent.com/647500/153626210-5f52ec1c-da9a-445d-9c4c-0e0afb51af1d.png)

For ENTD, we actually see that the last category is off, but for me this might be more of a weighting error. The documentation of the ENTD clearly says that this is the categorie socioprofessionalle in 24 categories, so we need to take the starting number, which we do:
![image](https://user-images.githubusercontent.com/647500/153626188-dcce2585-9d04-416b-8aaa-dc9c4d8086dd.png)

Now for both Lyon (`cerema`) and Nantes, we have a problem for category 8, which is basically non-existent:
![image](https://user-images.githubusercontent.com/647500/153626450-29170507-0a54-498c-9a27-4caa5ef67dec.png)

![image](https://user-images.githubusercontent.com/647500/153626464-1af2dff1-cb85-4e36-9b75-26edb7624a7b.png)

**Comment by sebhoerl** [comment]
Aaaaand here is the fix described above. It is not perfect, but I think the remaining differences we can put on different methodologies / weighting of the data sets?

![image](https://user-images.githubusercontent.com/647500/153629709-64a89745-2a05-4ced-8089-584a9c1e6f58.png)

![image](https://user-images.githubusercontent.com/647500/153629744-3150a055-cce3-4244-b355-4262b1e22518.png)

**Comment by ouassimm** [comment]
Great! Thanks Sebastian.
One question: in Lyon, you are still using P9 as the variable that describes the PCS category. Should not we use P11 instead? According to your screenshot (https://user-images.githubusercontent.com/647500/153472818-63b6d964-bc86-480a-bce3-8207af730038.png) P11 is the right variable to describe the PCS in the CEREMA's version of EDGT Lyon.

For Nantes, P9 is the right variable to describe the PCS.

**Comment by sebhoerl** [comment]
Yes, but look at the screenshot above. There is no P11 in the EDGT Lyon, only P9. And then in the line of P9 the description says "P11", and then the last columns also refer to P11. And when I run it now with the fix I get the result plots as shown above. Those plots are directly generated from the debugging analysis stage that I was adding in the PR, and which uses directly the cleaned and filtered HTS output.

**Comment by ouassimm** [comment]
Thanks!
For me, the issue is solved.
